version: 2

models:
  - name: fct_tmae
    description: Fato mensal com metricas de atendimento emergencial na granularidade distribuidora por competencia.
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - sk_distribuidora
              - sk_tempo
    columns:
      - name: sk_distribuidora
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_distribuidora')
                field: sk_distribuidora
      - name: sk_tempo
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_tempo')
                field: sk_tempo
      - name: tmae
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
